### ISSUE TITLE
Obtain electronic integral derivatives directly from `Psi4Driver`

### ISSUE THREAD

**Issue by MartinBeseda** [qiskit-community/qiskit-nature#1134]
**Qiskit version:** 0.23.3
**Qiskit Nature version:** 0.6.0
**System version:** Ubuntu 20.04.5 LTS

I'm implementing a code heavily dependent on `ElectronicStructureProblem` class created by `Psi4Driver`. The point is, I need to obtain electronic integral derivatives from [Psi4](https://psicode.org/), i.e. to call functions [ao_oei_deriv1()](https://psicode.org/psi4manual/master/api/psi4.core.MintsHelper.html#psi4.core.MintsHelper.ao_oei_deriv1), [ao_tei_deriv1()](https://psicode.org/psi4manual/master/api/psi4.core.MintsHelper.html#psi4.core.MintsHelper.ao_tei_deriv1), etc.

So far I only found, that I can call `ElectronicStructureProblem.to_qcschema()` method, but that doesn't seem to provide these quantities, which have some input parameters.

So, is there any way to avoid calling Psi4 two times, once in `Psi4Driver` and the second time by Psi4 API, to obtain the gradients?

---

MWE containing gradients obtained directly from Psi4 API and a creation of Psi4Driver is here:
```
import psi4
import numpy as np
from qiskit_nature.second_q.drivers import Psi4Driver

geometry = [('N', [0.000000000000, 0.000000000000,  0.000000000000]),
            ('C', [0.000000000000, 0.000000000000,  1.498047000000]),
            ('H', [0.000000000000, -0.938765985000, 2.004775984000]),
            ('H', [0.000000000000, 0.938765985000,  2.004775984000]),
            ('H', [-0.744681452,   -0.131307432,    -0.634501434])]

psi4_geom = '\n'.join(f'{atom[0]} ' + ' '.join(str(x) for x in atom[1]) for atom in geometry)

psi4.set_options({'basis': 'sto-3g',
                  'reference': 'rhf',
                  'SCF_TYPE': 'pk'})
psi4.core.set_output_file('psi4-rhf.out', append=False)

psi4_e, psi4_wfn = psi4.energy('HF', molecule=psi4.geometry(psi4_geom, "PSI4 Molecule"), return_wfn=True, verbose=0)
psi4_mints = psi4.core.MintsHelper(psi4_wfn.basisset())

# Here I obtain EI gradients
ao_deriv1 = np.array(psi4_mints.ao_oei_deriv1(oei_type='OVERLAP', atom=0))


driver = Psi4Driver('molecule NCHHH {\nunits ang\n0 1\nN 0.0 0.0 0.0\nC 0.0 0.0 1.498047\nH 0.0 -0.938765985 2.004775984\nH 0.0 0.938765985 2.004775984\nH -0.744681452 -0.131307432 -0.634501434\nno_com\nno_reorient\n}\n\nset {\n basis sto-3g\n scf_type pk\n reference rhf\n}')
problem = driver.run()
qcschema = driver.to_qcschema()
# Any way to obtain EI gradients here?
```

**Comment by mrossinek** [comment]
The `Psi4Driver` has the code which is actually run "hidden" inside of [this template file](https://github.com/Qiskit/qiskit-nature/blob/main/qiskit_nature/second_q/drivers/psi4d/_template.txt). This is quite a legacy integration but there has not been time or interest to update it.

Ideally, we would have a Psi4 integration similar to the PySCF one [here](https://github.com/qiskit-community/qiskit-nature-pyscf). This would mean that you could write Psi4 code and then add quantum on-top or patch it into it. I did talk to some Psi4 devs in the past and while there was interest in such a plugin/joint repo, nothing has come of it yet due to time and other resource constraints.

Unless you want to get started with the development of a plugin like that one, in the meantime you probably have two options:
- modifying the `template.txt` file to fit your needs and patching whatever information you need into the QCSchema and extracting it yourself (although this approach probably does not scale well)
- a better approach would probably be to extract some core methods from that `template.txt` file and write them such that they generate needed data (either a QCSchema or an ElectronicStructureProblem directly) when given an `mints` object. How to get to the `mints` project would need to be figured out, too. You could then either add more methods to fit your needs or simply modify the ones you extracted.

If you have noticeable improvements coming out of this which you think could improve the state of the driver, please consider opening a PR. However, in the _very_ long run, I think the trend will be more towards plugin-like integrations and very minimal drivers purely for educational/getting started/testing purposes. There is just no way to expose all of the potential functionality from these complex codes via drivers whereas plugins leave the developer/user full flexibility in what they want to do.

**Comment by mrossinek** [comment]
That's great to hear! Let me look into getting that repo set up, it might take a while though as the relevant people are fairly busy at the moment :+1:

**Comment by MartinBeseda** [comment]
@mrossinek Of course, take your time :)

**Comment by mrossinek** [comment]
@MartinBeseda some news on this front:

- https://github.com/qiskit-community/qiskit-nature-psi4 is now ready for us to get started in. I did some preliminary infrastructure setup but some things like CI are not configured yet. I think for now we should be able to keep things rather minimal until we have them working
- I also tried reaching out via the public Qiskit Slack to you to discuss a few details offline

**Comment by MartinBeseda** [comment]
Hi @mrossinek ,
sorry for my late answer and thank you for arranging the repo.

I agree with "minimal" approach so far, at least for the next month, as I'll have much more time after finishing my current project in the end of June.

Also, how can I join the Qiskit Slack? I found some link, but it wasn't working anymore. Could I get some invite?

**Comment by mrossinek** [comment]
You can join the Qiskit slack via this link: https://qisk.it/join-slack
