### ISSUE TITLE
`BosonicOp.simplify` behaves incorrectly

### ISSUE THREAD

**Issue by mrossinek** [qiskit-community/qiskit-nature#1208]
### Environment

- **Qiskit Nature version**: `main` @ c616370a8e2e8c5667ad7fce2b532a893ec81baf
- **Python version**: Any
- **Operating system**: Any

### What is happening?

The `BosonicOp.simplify` method makes a wrong assumption and therefore results in wrongly simplified operators.

### How can we reproduce the issue?

```python
>>> from qiskit_nature.second_q.operators import BosonicOp
>>> op = BosonicOp({'+_0 -_0 -_1 +_0': 1})
>>> op.simplify()
BosonicOp({'+_0 -_1': (2+0j)}, num_modes=2, )
```

### What should happen?

The operator in the example above cannot be simplified further.

### Any suggestions?

The problem is the a wrong assumption built into the `BosonicOp._simplify_label` method.
It results from how we simplify a number operator which in general should be:

$$
\hat{a}^\dagger \hat{a} | n \rangle = n | n \rangle
$$

In the fermionic case, $n$ can be either $0$ or $1$, but in the bosonic case it is indeed general. That is why the simplification we took over from the fermionic case is wrong.
A good example to show this is also the following:

$$
\hat{a}^\dagger \hat{a} \hat{a}^\dagger \hat{a} | n \rangle = n^2 | n \rangle
$$

In our operators, since we do not know what state $|n\rangle$ we apply them to, we cannot simplify this further. Thus, we have two options:

1. do not perform any simplification other than getting rid of zero-coefficient terms
2. implement a construct to specifically handle number operators (e.g. using parameters) and treat these separately all the way through the mapping down to the qubit level

Option 2 is a lot more involved and has many unclear aspects to it. Thus, we will go with option 1.
If at some point in the future we come up with a plan on how to realize option 2, then we can revisit this. But I do not consider this a high priority.

**Comment by ftroisi** [comment]
Yes I'm happy to work on it!

**Comment by ftroisi** [comment]
@mrossinek There's something we haven't really considered about the commutator.
## Issue
So currently the `simplify()` method for `BosonicOp` first performs `normal_order()` and then simplifies the operator.

If we remove the `normal_order()`, then we break the test for the commutator. In fact, currently we have:
```
>>> from qiskit_nature.second_q.operators import BosonicOp
>>> from qiskit_nature.second_q.operators.commutators import commutator
>>> commutator(BosonicOp({"-_0": 1}), BosonicOp({"+_0": 1}))
BosonicOp({'': (1+0j)}, num_modes=1, )
```
If we remove the normal_order we have:
```
>>> from qiskit_nature.second_q.operators import BosonicOp
>>> from qiskit_nature.second_q.operators.commutators import commutator
>>> commutator(BosonicOp({"-_0": 1}), BosonicOp({"+_0": 1}))
BosonicOp({'-_0 +_0': (1+0j), '+_0 -_0': (-1+0j)}, num_modes=1, )
```

Technically, both of them are correct, but the second case is not simplified and one would have to think whether it actually yields +1 or not. On the other hand, with the first case, we'll keep not having commutation between `simplify()` and `index_order()`.
This got me curious, so I tested the `FermioniOp` as well. The current behavior has the same issue as the `BosonicOp` without the `normal_order()`:

```
>>> from qiskit_nature.second_q.operators import FermionicOp
>>> from qiskit_nature.second_q.operators.commutators import anti_commutator
>>> commutator(FermionicOp({"-_0": 1}), FermionicOp({"+_0": 1}))
FermionicOp({'-_0 +_0': (1+0j), '+_0 -_0': (-1+0j)}, num_spin_orbitals=1, )
```

## My suggestion
In my opinion, the definition of `commutator` and `anti_commutator` should make use of the `normal_order()` and not of the `simplify()`. In fact currently it is:
```
def commutator(op_a: SparseLabelOp, op_b: SparseLabelOp) -> SparseLabelOp:
    return (op_a @ op_b - op_b @ op_a).simplify(atol=0)
def anti_commutator(op_a: SparseLabelOp, op_b: SparseLabelOp) -> SparseLabelOp:
    return (op_a @ op_b + op_b @ op_a).simplify(atol=0)
```
But it should be:
```
def commutator(op_a: SparseLabelOp, op_b: SparseLabelOp) -> SparseLabelOp:
    return (op_a @ op_b - op_b @ op_a).normal_order()
def anti_commutator(op_a: SparseLabelOp, op_b: SparseLabelOp) -> SparseLabelOp:
    return (op_a @ op_b + op_b @ op_a).normal_order()
```
If you do that, you obtain the following:
```
>>> from qiskit_nature.second_q.operators import BosonicOp, FermionicOp
>>> f_m = FermionicOp({"-_0": 1})
>>> f_p = FermionicOp({"+_0": 1})
>>> (f_m @ f_p + f_p @ f_m).normal_order()
FermionicOp({'': 1.0}, num_spin_orbitals=1, )

>>> b_m = BosonicOp({"-_0": 1})
>>> b_p = BosonicOp({"+_0": 1})
>>> (b_m @ b_p - b_p @ b_m).normal_order()
BosonicOp({'': 1}, num_modes=1, )
```
Which is what one would like to see. With this new definition we can safely remove the `normal_order()` from the `simplify()` of the `BosonicOp`, so that we finally have commutation with `index_order()`

What's your opinion?

**Comment by mrossinek** [comment]
I think extracting `normal_order` from `simplify` is desired.
But I think we should still call `simplify` as part of `commutator`. Maybe we can do:
```python
return (op_a @ op_b - op_b @ op_a).normal_order().simplify(atol=0)
```
Because I do not think that `normal_order` guarantees to remove zero-valued coefficients after performing the reordering.

**Comment by ftroisi** [comment]
Good point, let's go for 
```python
return (op_a @ op_b - op_b @ op_a).normal_order().simplify(atol=0)
```
