### ISSUE TITLE
Inconsistent behavior of `HartreeFock` and `UCC` for fully occupied orbitals

### ISSUE THREAD

**Issue by julenl** [qiskit-community/qiskit-nature#1277]
### Environment

- **Qiskit Nature version**: '0.7.0'
- **Python version**:  3.10.12
- **Operating system**: Ubuntu

### What is happening?

Trying to run a UCC calculation on noble gas dimmers does not seem to work.

### How can we reproduce the issue?

``` python
from qiskit_nature.second_q.drivers import PySCFDriver

driver = PySCFDriver( atom='He 0 0 0; He 0 0 5.2' )
problem = driver.run()

from qiskit_nature.second_q.mappers import JordanWignerMapper
mapper = JordanWignerMapper()

from qiskit_algorithms.optimizers import SLSQP
from qiskit_algorithms import VQE
from qiskit.primitives import Estimator
from qiskit_nature.second_q.circuit.library import HartreeFock, UCCSD

ansatz = UCCSD(
    problem.num_spatial_orbitals,
    problem.num_particles,
    mapper,
    initial_state=HartreeFock(
        problem.num_spatial_orbitals,
        problem.num_particles,
        mapper,
    ),
)

print(ansatz.num_parameters)
```
Returns:
```
ValueError: The number of spatial orbitals 2must be greater than number of particles of any spin kind (2, 2).
```

### What should happen?

The ansatz should work also for fully occupied orbitals.

### Any suggestions?

I have noticed that there is some incoherence between two similar validations:
- On file qiskit_nature/second_q/circuit/library/ansatzes/ucc.py it says:
  _"The number of spatial orbitals 2 must be greater than the number of particles of any spin kind (2,2)"_
  And the condition is: `if any(n >= self.num_spatial_orbitals for n in self.num_particles):`
   
- While on file qiskit_nature/second_q/circuit/library/initial_states/hartree_fock.py it says:
  _"The number of spatial orbitals 2 must be greater than or equal to the number of particles of any spin kind (2,2)"_
  And the condition is: `if any(n > self.num_spatial_orbitals for n in self.num_particles):`

The text on the second one says "_greater than or equal_" but the condition only has a ">", and it works.
But the ucc one says "_greater than_" and the condition is ">=", so it does not work for any noble gas.

I tried removing the "=" from the ">=" for ucc, but then the operator turns for some reason into a list at some point and crashes.

**Comment by mrossinek** [comment]
Besides the fact that, when both spin registers (alpha and beta) are fully occupied, UCCSD is not really going to give you an improved result, I agree that the exception logic around this could be improved a bit. Especially, since this failure also occurs when e.g. only the alpha spin register is completely filled while the beta-spin is not. I ran into the past and in such cases simply disabled the check because the code works fine (for when at least the beta-spin is not fully occupied).

> I tried removing the "=" from the ">=" for ucc, but then the operator turns for some reason into a list at some point and crashes. 

The "problem" is, that a filled register leads to empty lists of excitations which might need to be handled differently in pieces of the code. But that should not be difficult to fix.

Would you be interested in opening a PR which includes the following?
- [ ] makes the checks (and raised warnings/errors) in HartreeFock and all UCC subclasses consistent
- [ ] (optional) adds support for fully occupied spin registers
    - this should include any changes required to make this work as intended
    - as well as a unittest to ensure that this continues to work

**Comment by julenl** [comment]
I'll be more than happy to try, but I will need some assistance.
